version: '3.8'

services: 
  app:
    container_name: myclean
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - postgres
  
  postgres:
    container_name: postgres-db
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: