# Generated by Django 5.1.6 on 2025-02-13 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='is_approved',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='post_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
