# Generated by Django 5.1.7 on 2025-03-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_rename_is_approved_serviceprovider_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='General', max_length=15),
        ),
    ]
