# Generated by Django 5.1.7 on 2025-03-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_availabilityslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='start_time',
        ),
    ]
